
server:
  port: ${PORT:9090}

resilience4j.circuitbreaker:
  circuitbreaker:
    instances:
      list:
        registerHealthIndicator: true
        ringBufferSizeInClosedState: 5
        ringBufferSizeInHalfOpenState: 3
        waitDurationInOpenState: 10s
        failureRateThreshold: 50

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include:
          - '*'
  health:
    circuitbreakers:
      enabled: true
    bulkhead:
      enabled: true
    ratelimiters:
      enabled: true
    db:
      enabled: false
    diskspace:
      enabled: true
