
server:
  port: 9595
spring:
  r2dbc:
    username: root
    password: root
    url: r2dbc:postgresql://localhost:5432/test
  application:
    name: inventario
  kafka:
    bootstrap-servers:
      - localhost:9092
  cloud:
    stream:
      binders:
        kafka:
          type: kafka
      bindings:
        input-estoque:
          destination: topic-order-estoque
          group: '${spring.application.name}'
        output-status:
          destination: topic-order-status
          group: '${spring.application.name}'
      kafka:
        input-estoque:
          destination: topic-order-estoque
          group: '${spring.application.name}'
          consumer:
            autoCommitOffset: true

app:
  topic: topic-order-estoque
  status: topic-order-status